### ISSUE TITLE
Problem in finding model paths

### ISSUE THREAD

**Issue by BurykinNikolay** [innightwolfsleep/llama-cpp-telegram_bot#2]
I keep running into the model directory error.

I put ggml-vic13b-q5_0.bin into llama-cpp-telegram_bot/models
Change directory way in  telegram_llm_model_path.txt  from "models\<model_file_name.bin>" to "models/ggml-vic13b-q5_0.bin"

After run  python3 main.py I see this log:

<img width="968" alt="image" src="https://user-images.githubusercontent.com/28725659/235517824-036c15d2-44fb-463f-8ea0-ab2b441eb2e4.png">

**Comment by innightwolfsleep** [comment]
Hi!
Readme updated. It was incorectly cloned from neighbour project.

First, move (cd) to dir where main.py placed 
Then - python main.py
