### ISSUE TITLE
How to get two bots chatting to each other

### ISSUE THREAD

**Issue by gjmulder** [innightwolfsleep/llama-cpp-telegram_bot#7]
Hiya @innightwolfsleep thanks for the bot code!

You might have seen my reply to your [Telegram bot chat wrapper](https://github.com/abetlen/llama-cpp-python/discussions/128).

Now that I have Dockerised your bot code I have two bots in the same room. However, they seem to not respond to each other's output. Is there a way to get them to see each other?

**Comment by innightwolfsleep** [comment]
Have nothing to add here... 

python-telegram-bot library not provide user api, so it is imposible to make fake "telegram user" with my code. Need migrate to another framework to provide this feature.
